name = "hello-friendly"
license = "MIT"
licenselink = "https://github.com/niklas-heer/hugo-theme-hello-friendly/blob/master/LICENSE.md"
description = "A simple theme for Hugo. That's it."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "Niklas Heer"
  homepage = "https://nheer.io"
  twitter = "https://twitter.com/niklas_heer"

[original]
  name = "hello-friend-ng"
  homepage = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
  repo = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
