baseURL = "https://nheer.com"
title   = "Niklas Heer"

DefaultContentLanguage = "en"
theme = "hello-friendly"

pygmentsCodefences = true
pygmentsUseClasses = false
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "dracula"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
disqusShortname = "nheer"

buildDrafts  = false
buildFuture  = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Niklas Heer"

[blackfriday]
  hrefTargetBlank = true

# [taxonomies]
#   tag      = "tags"
#   category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Niklas Heer"
  keywords = "homepage, blog, science, informatics, development, programming, projects, cloud, software, devops, leadership, security, quality"
  images = [""]

  homeSubtitle = "Leadership, DevSecOps and Quality"
  homeLogo = "/assets/images/nheer_logo.svg"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/niklas-heer/nheer.io/commit/"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Maximal number of rating
  maxRating = 5

  [params.logo]
    logoText     = "nheer"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/niklas_heer/"

  [[params.social]]
    name = "telegram"
    url  = "https://t.me/niklas_heer"

  [[params.social]]
    name = "email"
    url  = "mailto:me@nheer.io"

  [[params.social]]
    name = "github"
    url  = "https://github.com/niklas-heer/"

  [[params.social]]
    name = "goodreads"
    url  = "https://www.goodreads.com/user/show/72344845-niklas-heer"

  [[params.social]]
    name = "linkedin"
    url  = "https://de.linkedin.com/in/niklas-heer-b89364b8"

  [[params.social]]
    name = "xing"
    url  = "https://www.xing.com/profile/Niklas_Heer"

[languages]
  [languages.en]
    subtitle  = "Homepage & Blog"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [[languages.en.menu.main]]
      identifier = "about"
      weight     = -200
      name       = "About"
      url        = "about/"

    [[languages.en.menu.main]]
      identifier = "posts"
      weight     = -190
      name       = "Blog"
      url        = "posts/"

    # [[languages.en.menu.main]]
    #   identifier = "work"
    #   weight     = -180
    #   name       = "Work"
    #   url        = "work/"

    [[languages.en.menu.main]]
      identifier = "books"
      weight     = -170
      name       = "Books"
      url        = "books/"

  [languages.de]
    subtitle  = "Homepage & Blog"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [[languages.de.menu.main]]
      identifier = "about"
      weight     = -200
      name       = "Über mich"
      url        = "about/"

    [[languages.de.menu.main]]
      identifier = "blog"
      weight     = -190
      name       = "Blog"
      url        = "posts/"

    # [[languages.de.menu.main]]
    #   identifier = "work"
    #   weight     = -180
    #   name       = "Arbeiten"
    #   url        = "work/"

    [[languages.de.menu.main]]
      identifier = "books"
      weight     = -170
      name       = "Bücher"
      url        = "books/"
