baseURL = "https://nheer.com"
title   = "Niklas Heer"

DefaultContentLanguage = "en"
theme = "hello-friendly"

pygmentsCodefences = true
pygmentsUseClasses = false
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "dracula"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

buildDrafts  = false
buildFuture  = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Niklas Heer"

[blackfriday]
  hrefTargetBlank = true

# [taxonomies]
#   tag      = "tags"
#   category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Niklas Heer"
  keywords = "homepage, blog, science, informatics, development, programming, projects, cloud, software"
  images = [""]

  homeSubtitle = "DevOps and Quality"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/niklas-heer/nheer.io/commit/"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Maximal number of rating
  maxRating = 5

  [params.logo]
    logoText     = "nheer"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/niklas_heer/"

  [[params.social]]
    name = "email"
    url  = "mailto:niklas.heer@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/niklas-heer/"

  [[params.social]]
    name = "linkedin"
    url  = "https://de.linkedin.com/in/niklas-heer-b89364b8"

[languages]
  [languages.en]
    subtitle  = "Homepage & Blog"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.de]
    subtitle  = "Homepage & Blog"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Blog"
    url        = "posts/"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"
  [[menu.main]]
    identifier = "reading"
    name       = "Reading"
    url        = "reading/"
